/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as LinkingRouteImport } from './routes/linking'
import { Route as LocalRouteImport } from './routes/local'
import { Route as PackRouteImport } from './routes/pack'
import { Route as StrategyRouteImport } from './routes/strategy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkingRoute = LinkingRouteImport.update({
  id: '/linking',
  path: '/linking',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const PackRoute = PackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/blog': typeof BlogRoute
  '/clusters': typeof ClustersRoute
  '/keywords': typeof KeywordsRoute
  '/linking': typeof LinkingRoute
  '/local': typeof LocalRoute
  '/pack': typeof PackRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/blog': typeof BlogRoute
  '/clusters': typeof ClustersRoute
  '/keywords': typeof KeywordsRoute
  '/linking': typeof LinkingRoute
  '/local': typeof LocalRoute
  '/pack': typeof PackRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/blog': typeof BlogRoute
  '/clusters': typeof ClustersRoute
  '/keywords': typeof KeywordsRoute
  '/linking': typeof LinkingRoute
  '/local': typeof LocalRoute
  '/pack': typeof PackRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/blog'
    | '/clusters'
    | '/keywords'
    | '/linking'
    | '/local'
    | '/pack'
    | '/strategy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/blog'
    | '/clusters'
    | '/keywords'
    | '/linking'
    | '/local'
    | '/pack'
    | '/strategy'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/blog'
    | '/clusters'
    | '/keywords'
    | '/linking'
    | '/local'
    | '/pack'
    | '/strategy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  BlogRoute: typeof BlogRoute
  ClustersRoute: typeof ClustersRoute
  KeywordsRoute: typeof KeywordsRoute
  LinkingRoute: typeof LinkingRoute
  LocalRoute: typeof LocalRoute
  PackRoute: typeof PackRoute
  StrategyRoute: typeof StrategyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linking': {
      id: '/linking'
      path: '/linking'
      fullPath: '/linking'
      preLoaderRoute: typeof LinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack': {
      id: '/pack'
      path: '/pack'
      fullPath: '/pack'
      preLoaderRoute: typeof PackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  BlogRoute: BlogRoute,
  ClustersRoute: ClustersRoute,
  KeywordsRoute: KeywordsRoute,
  LinkingRoute: LinkingRoute,
  LocalRoute: LocalRoute,
  PackRoute: PackRoute,
  StrategyRoute: StrategyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
